version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: problemz
      POSTGRES_USER: problemz
      POSTGRES_PASSWORD: abc123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: problemz-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/problemz
      SPRING_DATASOURCE_USERNAME: problemz
      SPRING_DATASOURCE_PASSWORD: abc123
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres_data:
